quarkus.http.port=${PORT}

# GCP Configuration
quarkus.google.cloud.project-id=${GCP_PROJECT_ID}
%test.quarkus.google.cloud.project-id=test-project
quarkus.google.cloud.spanner.instance-id=${GCP_SPANNER_INSTANCE_ID}
quarkus.google.cloud.spanner.database-id=${GCP_SPANNER_DATABASE_ID}

### Graceful Shutdown Configuration
# Maximum time to wait for active requests to complete during shutdown
quarkus.shutdown.timeout=${SHUTDOWN_TIMEOUT}

# Enable a delay between shutdown signal and actual shutdown initiation.
# When enabled:
# 1. Application will wait 'quarkus.shutdown.delay' seconds before beginning the shutdown process
# 2. SmallRye Health will immediately change readiness probe status to DOWN
# This allows infrastructure to detect the impending shutdown and stop
# routing new traffic to this instance before shutdown begins
quarkus.shutdown.delay-enabled=${SHUTDOWN_DELAY_ENABLED}

# Number of seconds to wait after receiving shutdown signal before beginning the shutdown process
# During this time:
# - Readiness probe will report DOWN
# - Application continues to process existing requests
# - Infrastructure should detect DOWN status and stop routing new traffic
quarkus.shutdown.delay=${SHUTDOWN_DELAY}

# Disable JAR packaging for native mode
quarkus.package.jar.enabled=false
%dev.quarkus.package.jar.enabled=true
%test.quarkus.package.jar.enabled=true

### Logging Configuration
# Enable JSON logging for easy parsing in Cloud Run
quarkus.log.console.json.enabled=true
%dev.quarkus.log.console.json.enabled=false
%dev.quarkus.log.console.json.pretty-print=true

# Define log levels
quarkus.log.level=WARN
%dev.quarkus.log.level=INFO
%prod.quarkus.log.level=ERROR
%test.quarkus.log.level=OFF
